services:
  app:
    image: ghcr.io/marcosgcr3/ethical-crypto:v1
    pull_policy: always
    # No necesitamos mapear puertos hacia afuera, Traefik se encarga
    expose:
      - "3000"
    volumes:
      - ./public/images:/app/public/images
    env_file:
      - .env
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crypto-app.rule=Host(`ethical-crypto.com`)"
      - "traefik.http.routers.crypto-app.entrypoints=websecure"
      - "traefik.http.routers.crypto-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.crypto-app.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
